FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1

WORKDIR /app
COPY . .
RUN uv sync --frozen --package snake-arena-api

ENTRYPOINT ["uv", "run", "--frozen", "--no-sync", "--package", "snake-arena-api", "api"]
